"""
AgentPrahari & Live Verified RAG Model Context Protocol (MCP) Server.
Standard JSON-RPC 2.0 stdio server compliant with Anthropic MCP protocol specifications.
Can be plugged directly into Claude Desktop, Cursor, Antigravity, or any MCP client.
"""

import sys
import json
import os
from pathlib import Path

# Add project root to sys.path so backend imports work smoothly
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from agentprahari import AgentPrahari
from backend.services.live_rag.engine import LiveVerifiedRAGEngine
from backend.services.content_pipeline.orchestrator import MultiAgentContentOrchestrator

# Initialize core services
prahari = AgentPrahari.custom(
    enable_pii=True,
    enable_prompt_injection=True,
    enable_output_secrets=True,
    enable_toxicity=True
)
live_rag_engine = LiveVerifiedRAGEngine()
pipeline_orchestrator = MultiAgentContentOrchestrator(max_revisions=1)

MCP_TOOLS = [
    {
        "name": "agentprahari_validate_input",
        "description": "Inspects and sanitizes user prompts or agent inputs using AgentPrahari. Detects prompt injections, jailbreaks, and redacts sensitive PII (emails, phone numbers, API keys).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "prompt": {
                    "type": "string",
                    "description": "The user prompt or agent input text to validate."
                },
                "client_id": {
                    "type": "string",
                    "description": "Optional client or session identifier for rate tracking.",
                    "default": "default"
                }
            },
            "required": ["prompt"]
        }
    },
    {
        "name": "agentprahari_validate_output",
        "description": "Validates model-generated responses to prevent secret leaks, ungrounded hallucinations, and policy violations.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "output_text": {
                    "type": "string",
                    "description": "The text generated by an LLM or agent."
                },
                "prompt": {
                    "type": "string",
                    "description": "The original user prompt (optional)."
                },
                "context": {
                    "type": "string",
                    "description": "The reference context or retrieved chunks to check groundedness against (optional)."
                }
            },
            "required": ["output_text"]
        }
    },
    {
        "name": "search_verified_live_news",
        "description": "Queries real-time live news and RSS feeds with exponential time-decay freshness scoring, semantic deduplication, and cross-source verification (>= 2 independent source domains).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Topic or query to research across live news feeds (e.g. 'DeepSeek LLM release', 'Federal Reserve rate cut')."
                },
                "max_articles": {
                    "type": "integer",
                    "description": "Maximum number of unique fresh articles to include.",
                    "default": 8
                }
            },
            "required": ["query"]
        }
    },
    {
        "name": "generate_verified_content",
        "description": "Executes an autonomous 4-agent content pipeline (Researcher -> Verifier -> Writer -> Editor) with multi-source fact-checking, citation enforcement, and editorial revision cycles.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "topic": {
                    "type": "string",
                    "description": "The subject matter to research and write a verified report on."
                },
                "target_audience": {
                    "type": "string",
                    "description": "Target audience style (e.g. 'Software Engineers', 'Executive Leadership').",
                    "default": "Industry Professionals & Developers"
                }
            },
            "required": ["topic"]
        }
    }
]


def handle_tool_call(name: str, arguments: dict) -> dict:
    """Executes the requested tool and returns a standard MCP result payload."""
    try:
        if name == "agentprahari_validate_input":
            prompt = arguments.get("prompt", "")
            client_id = arguments.get("client_id", "default")
            res = prahari.validate_input(prompt, client_id=client_id)
            return {
                "content": [
                    {
                        "type": "text",
                        "text": json.dumps({
                            "is_valid": res.is_valid,
                            "decision": str(res.decision),
                            "sanitized_content": res.sanitized_content,
                            "violations": [
                                {
                                    "rule_id": v.rule_id,
                                    "message": v.message,
                                    "severity": str(v.severity),
                                    "matched_content": v.matched_content
                                }
                                for v in res.violations
                            ],
                            "rejection_reason": res.rejection_reason
                        }, indent=2)
                    }
                ]
            }

        elif name == "agentprahari_validate_output":
            output_text = arguments.get("output_text", "")
            prompt = arguments.get("prompt")
            context = arguments.get("context")
            res = prahari.validate_output(output_text, prompt=prompt, context=context)
            return {
                "content": [
                    {
                        "type": "text",
                        "text": json.dumps({
                            "is_valid": res.is_valid,
                            "decision": str(res.decision),
                            "sanitized_content": res.sanitized_content,
                            "violations": [v.message for v in res.violations],
                            "rejection_reason": res.rejection_reason
                        }, indent=2)
                    }
                ]
            }

        elif name == "search_verified_live_news":
            query = arguments.get("query", "")
            max_articles = int(arguments.get("max_articles", 8))
            rag_res = live_rag_engine.query(query, max_articles=max_articles)
            return {
                "content": [
                    {
                        "type": "text",
                        "text": json.dumps(rag_res, indent=2)
                    }
                ]
            }

        elif name == "generate_verified_content":
            topic = arguments.get("topic", "")
            audience = arguments.get("target_audience", "Industry Professionals & Developers")
            state = pipeline_orchestrator.execute_pipeline(topic, target_audience=audience)
            return {
                "content": [
                    {
                        "type": "text",
                        "text": json.dumps({
                            "topic": state.topic,
                            "status": state.status,
                            "final_article": state.final_output,
                            "verified_claims": [c.model_dump() for c in state.verified_claims],
                            "citations": [c.model_dump() for c in state.citations],
                            "final_score": state.critiques[-1].score if state.critiques else 0,
                            "iterations": state.current_iteration + 1,
                            "execution_time_seconds": state.execution_time_seconds
                        }, indent=2)
                    }
                ]
            }
        else:
            return {
                "isError": True,
                "content": [{"type": "text", "text": f"Unknown tool: {name}"}]
            }

    except Exception as e:
        return {
            "isError": True,
            "content": [{"type": "text", "text": f"Tool execution failed: {str(e)}"}]
        }


def run_stdio_server():
    """Runs standard line-delimited JSON-RPC loop over sys.stdin / sys.stdout."""
    for line in sys.stdin:
        if not line.strip():
            continue
        try:
            req = json.loads(line)
            req_id = req.get("id")
            method = req.get("method")
            params = req.get("params", {})

            if method == "initialize":
                res = {
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": {
                        "protocolVersion": "2024-11-05",
                        "serverInfo": {
                            "name": "agentprahari-live-rag-mcp",
                            "version": "1.0.0"
                        },
                        "capabilities": {
                            "tools": {}
                        }
                    }
                }
            elif method == "tools/list":
                res = {
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": {
                        "tools": MCP_TOOLS
                    }
                }
            elif method == "tools/call":
                tool_name = params.get("name")
                tool_args = params.get("arguments", {})
                tool_result = handle_tool_call(tool_name, tool_args)
                res = {
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": tool_result
                }
            elif method == "notifications/initialized":
                continue  # No reply needed for notifications
            else:
                res = {
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "error": {
                        "code": -32601,
                        "message": f"Method not found: {method}"
                    }
                }

            sys.stdout.write(json.dumps(res) + "\n")
            sys.stdout.flush()

        except Exception as err:
            err_res = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {
                    "code": -32700,
                    "message": f"Parse error: {str(err)}"
                }
            }
            sys.stdout.write(json.dumps(err_res) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    run_stdio_server()
